Bump to 4.0.2-1.20.1
Fixes an issue where the myLoot container does not have the same
properties as the original container, but we try adding non-existing
properties.  Unfortunately, this means it's possible the myLoot
container won't have all of the same features as the original, if it's
some modded container with different properties.

For example:

[23:09:35] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalArgumentException: Cannot set property
class_2746{name=ancient, clazz=class java.lang.Boolean, values=[true,
false]} as it does not exist in Block{myloot:loot_chest}
	at net.minecraft.class_2688.method_11657(class_2688.java:122)
	~[client-intermediary.jar:?]
		at
		org.spoorn.myloot.core.LootableContainerReplacer.lambda$registerTickCallback$2(LootableContainerReplacer.java:137)
		~[myloot-4.0.1-1.20.1.jar:?]